export const ReasonCodes = {
  // Identity (WHO)
  IDENTITY_MISSING_VERIFIED_HUMAN: 'IDENTITY_MISSING_VERIFIED_HUMAN',
  IDENTITY_NO_CREDENTIALS_PROVIDED: 'IDENTITY_NO_CREDENTIALS_PROVIDED',

  // Integrity (WHAT)
  INTEGRITY_TIMELINE_INCONSISTENT: 'INTEGRITY_TIMELINE_INCONSISTENT',
  INTEGRITY_FRAUD_PATTERN_HIGH: 'INTEGRITY_FRAUD_PATTERN_HIGH',
  INTEGRITY_FRAUD_PATTERN_MEDIUM: 'INTEGRITY_FRAUD_PATTERN_MEDIUM',
  INTEGRITY_LLM_CONFIDENCE_LOW: 'INTEGRITY_LLM_CONFIDENCE_LOW',
  INTEGRITY_CLAIM_AMOUNT_UNUSUALLY_HIGH: 'INTEGRITY_CLAIM_AMOUNT_UNUSUALLY_HIGH',
  INTEGRITY_REFUND_AMOUNT_ABOVE_THRESHOLD: 'INTEGRITY_REFUND_AMOUNT_ABOVE_THRESHOLD',

  // Evidence (PROOF)
  EVIDENCE_NONE_PROVIDED: 'EVIDENCE_NONE_PROVIDED',
  EVIDENCE_DEEPFAKE_DETECTED: 'EVIDENCE_DEEPFAKE_DETECTED',
  EVIDENCE_DEEPFAKE_PROVIDER_UNAVAILABLE: 'EVIDENCE_DEEPFAKE_PROVIDER_UNAVAILABLE',
  EVIDENCE_METADATA_INCONSISTENT: 'EVIDENCE_METADATA_INCONSISTENT',
} as const;

export type ReasonCode = (typeof ReasonCodes)[keyof typeof ReasonCodes];

export function stableSortReasonCodes(codes: Iterable<string>): string[] {
  return Array.from(new Set(Array.from(codes).filter(Boolean))).sort((a, b) => a.localeCompare(b));
}
