export { CredVerse } from './client.js';
export type {
  CredVerseClientOptions,
  IngestReputationEventRequest,
  CandidateVerificationSummary,
  VerificationEvidence,
  ProofGenerationRequestContract,
  ProofGenerationResultContract,
  ProofGenerationResultWithCode,
  ProofMetadataRequest,
  ProofMetadataResult,
  ProofVerificationRequestContract,
  ProofVerificationResultContract,
  ProofVerificationResultWithCode,
  ReputationCategoryContract,
  ReputationEventContract,
  ReputationProfileContract,
  ReputationScoreContract,
  ReputationShareGrantRequest,
  RevocationWitnessContract,
  SafeDateScoreContract,
  TrustVertical,
  VerifyDecision,
  VerifyRequest,
  VerifyResult,
} from './types.js';
