"""
Diet Plan Model - AI-generated personalized nutrition plans
"""
from datetime import datetime
from sqlalchemy import Column, String, Integer, DateTime, Boolean, Text, ForeignKey, Float
from sqlalchemy.orm import relationship

from app.database import Base
from app.db_types import GUID, JSONType, generate_uuid


class DietPlan(Base):
    """
    Personalized diet/nutrition plan for a member.
    Generated by AI based on goals, preferences, and progress.
    """
    __tablename__ = "diet_plans"
    
    id = Column(GUID(), primary_key=True, default=generate_uuid)
    member_id = Column(GUID(), ForeignKey("members.id"), nullable=False, index=True)
    
    # Week tracking
    week_number = Column(Integer, nullable=False)
    
    # Calorie/Macro targets
    daily_calories = Column(Integer, nullable=False)  # Target kcal
    protein_grams = Column(Integer, nullable=False)   # Protein target
    carbs_grams = Column(Integer, nullable=False)     # Carb target
    fat_grams = Column(Integer, nullable=False)       # Fat target
    
    # The actual meal plan (stored as JSON)
    plan_json = Column(JSONType(), nullable=False)
    """
    plan_json structure:
    {
        "meals": {
            "breakfast": {
                "name": "Protein Oatmeal",
                "calories": 350,
                "protein": 25,
                "items": [
                    "1 cup oats",
                    "1 scoop whey protein",
                    "1 banana",
                    "1 tbsp peanut butter"
                ],
                "alternatives": [
                    "Egg white omelette with toast",
                    "Protein smoothie bowl"
                ]
            },
            "mid_morning_snack": {...},
            "lunch": {...},
            "evening_snack": {...},
            "dinner": {...},
            "pre_workout": {...},
            "post_workout": {...}
        },
        "hydration": "3-4 liters of water",
        "supplements": [
            {"name": "Whey Protein", "timing": "post-workout"},
            {"name": "Multivitamin", "timing": "with breakfast"}
        ],
        "tips": [
            "Avoid sugar after 6pm",
            "Eat protein with every meal"
        ]
    }
    """
    
    # Status
    is_current = Column(Boolean, default=True)
    
    # Adaptation tracking
    adaptation_reason = Column(Text, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=True)
    
    # Relationships
    member = relationship("Member", back_populates="diet_plans")
    
    def __repr__(self):
        return f"<DietPlan {self.daily_calories}kcal for {self.member_id}>"
    
    @property
    def macro_ratio(self) -> dict:
        """Get macro ratio as percentages"""
        total = (self.protein_grams * 4 + self.carbs_grams * 4 + self.fat_grams * 9)
        if total == 0:
            return {"protein": 0, "carbs": 0, "fat": 0}
        return {
            "protein": round((self.protein_grams * 4 / total) * 100),
            "carbs": round((self.carbs_grams * 4 / total) * 100),
            "fat": round((self.fat_grams * 9 / total) * 100)
        }


class WeightLog(Base):
    """
    Track member weight over time.
    Used for progress tracking and plan adaptation.
    """
    __tablename__ = "weight_logs"
    
    id = Column(GUID(), primary_key=True, default=generate_uuid)
    member_id = Column(GUID(), ForeignKey("members.id"), nullable=False, index=True)
    
    weight_kg = Column(Float, nullable=False)
    logged_at = Column(DateTime, default=datetime.utcnow)
    
    # Optional context
    time_of_day = Column(String(20), nullable=True)  # morning/evening
    notes = Column(Text, nullable=True)
    
    def __repr__(self):
        return f"<WeightLog {self.weight_kg}kg at {self.logged_at}>"
