"""
Workout Plan Model - AI-generated personalized workout plans
"""
from datetime import datetime
from sqlalchemy import Column, String, Integer, DateTime, Boolean, Text, ForeignKey
from sqlalchemy.orm import relationship

from app.database import Base
from app.db_types import GUID, JSONType, generate_uuid


class WorkoutPlan(Base):
    """
    Weekly workout plan for a member.
    Generated by AI based on goals, progress, and adaptations.
    """
    __tablename__ = "workout_plans"
    
    id = Column(GUID(), primary_key=True, default=generate_uuid)
    member_id = Column(GUID(), ForeignKey("members.id"), nullable=False, index=True)
    
    # Week tracking
    week_number = Column(Integer, nullable=False)  # Which week of their journey
    
    # The actual plan (stored as JSON)
    plan_json = Column(JSONType(), nullable=False)
    """
    plan_json structure:
    {
        "focus": "Fat Burning & Conditioning",
        "total_days": 5,
        "days": {
            "monday": {
                "type": "Upper Body",
                "duration_mins": 45,
                "intensity": "medium",
                "exercises": [
                    {
                        "id": "bench_press",
                        "name": "Bench Press",
                        "sets": 3,
                        "reps": "10-12",
                        "rest_secs": 60,
                        "notes": "Control the descent",
                        "tutorial_id": "chest/bench_press"
                    }
                ],
                "warmup": [...],
                "cooldown": [...]
            },
            ...
        }
    }
    """
    
    # Status
    is_current = Column(Boolean, default=True)  # Active plan for this member
    
    # Adaptation tracking
    adaptation_reason = Column(Text, nullable=True)
    """
    Examples:
    - "Increased intensity due to consistent completion"
    - "Added rest day - energy levels low"
    - "Plateau breaker - changed routine"
    """
    
    # Metrics
    completion_rate = Column(Integer, default=0)  # % of workouts completed this week
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=True)  # When this plan ends
    
    # Relationships
    member = relationship("Member", back_populates="workout_plans")
    
    def __repr__(self):
        return f"<WorkoutPlan Week {self.week_number} for {self.member_id}>"
    
    @property
    def workout_days(self) -> list:
        """Get list of days with workouts"""
        if not self.plan_json or "days" not in self.plan_json:
            return []
        return list(self.plan_json["days"].keys())
    
    @property
    def total_exercises(self) -> int:
        """Count total exercises across all days"""
        if not self.plan_json or "days" not in self.plan_json:
            return 0
        count = 0
        for day_data in self.plan_json["days"].values():
            count += len(day_data.get("exercises", []))
        return count


class WeeklyCheckin(Base):
    """
    Weekly progress check-in from member.
    Used to adapt plans based on progress.
    """
    __tablename__ = "weekly_checkins"
    
    id = Column(GUID(), primary_key=True, default=generate_uuid)
    member_id = Column(GUID(), ForeignKey("members.id"), nullable=False, index=True)
    
    # Week info
    week_start = Column(DateTime, nullable=False)
    week_number = Column(Integer, nullable=False)
    
    # Progress data
    weight_kg = Column(Integer, nullable=True)  # Stored as grams for precision
    energy_level = Column(Integer, nullable=True)  # 1-5 rating
    diet_compliance = Column(String(20), nullable=True)  # full/mostly/poor
    sleep_quality = Column(Integer, nullable=True)  # 1-5 rating
    stress_level = Column(Integer, nullable=True)  # 1-5 rating
    
    # Workout completion
    workouts_planned = Column(Integer, default=0)
    workouts_completed = Column(Integer, default=0)
    
    # Notes
    notes = Column(Text, nullable=True)  # Any additional feedback
    
    # Adaptations triggered
    adaptations_applied = Column(JSONType(), nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<WeeklyCheckin Week {self.week_number} for {self.member_id}>"
    
    @property
    def completion_rate(self) -> float:
        """Calculate workout completion percentage"""
        if self.workouts_planned == 0:
            return 0.0
        return (self.workouts_completed / self.workouts_planned) * 100
