/**
 * Credential Types Service
 * Auto-generates credentials based on verified identity per PRD v3.1 Feature 1
 * 
 * Credential Types:
 * - verified_human: Default after liveness check
 * - age_18: Calculated from DOB on government ID
 * - age_21: Calculated from DOB on government ID
 * - location: Country + State from ID or GPS
 * - government_id: Encrypted ID document reference
 */

export interface CredentialType {
    type: string;
    name: string;
    description: string;
    icon: string;
    category: 'identity' | 'age' | 'location' | 'document' | 'professional';
    autoGenerated: boolean;
    requiresVerification: string[];
}

export interface UserCredential {
    id: string;
    userId: string;
    type: string;
    status: 'active' | 'expired' | 'revoked';
    issuedAt: Date;
    expiresAt: Date | null;
    usageCount: number;
    lastUsedAt: Date | null;
    data: Record<string, any>;
}

// Available credential types per PRD v3.1
export const CREDENTIAL_TYPES: CredentialType[] = [
    {
        type: 'verified_human',
        name: 'Verified Human',
        description: 'Proves you are a real, unique human',
        icon: '👤',
        category: 'identity',
        autoGenerated: true,
        requiresVerification: ['liveness']
    },
    {
        type: 'age_18',
        name: 'Age 18+',
        description: 'Proves you are 18 years or older',
        icon: '🎂',
        category: 'age',
        autoGenerated: true,
        requiresVerification: ['government_id']
    },
    {
        type: 'age_21',
        name: 'Age 21+',
        description: 'Proves you are 21 years or older',
        icon: '🎂',
        category: 'age',
        autoGenerated: true,
        requiresVerification: ['government_id']
    },
    {
        type: 'location',
        name: 'Location',
        description: 'Verified country and state',
        icon: '📍',
        category: 'location',
        autoGenerated: true,
        requiresVerification: ['government_id', 'gps']
    },
    {
        type: 'government_id',
        name: 'Government ID',
        description: 'Verified government-issued ID',
        icon: '🆔',
        category: 'document',
        autoGenerated: false,
        requiresVerification: ['digilocker', 'document_scan']
    },
    {
        type: 'email_verified',
        name: 'Email Verified',
        description: 'Verified email address',
        icon: '📧',
        category: 'professional',
        autoGenerated: true,
        requiresVerification: ['email_otp']
    },
    {
        type: 'phone_verified',
        name: 'Phone Verified',
        description: 'Verified phone number',
        icon: '📱',
        category: 'professional',
        autoGenerated: true,
        requiresVerification: ['phone_otp']
    }
];

/**
 * Generate credentials from verified identity data
 */
export function generateCredentialsFromIdentity(identityData: {
    livenessVerified: boolean;
    documentVerified: boolean;
    digilockerConnected: boolean;
    dob?: string;
    country?: string;
    state?: string;
    emailVerified?: boolean;
    phoneVerified?: boolean;
}): UserCredential[] {
    const credentials: UserCredential[] = [];
    const now = new Date();
    const oneYear = new Date(now.getTime() + 365 * 24 * 60 * 60 * 1000);

    // Verified Human - requires liveness
    if (identityData.livenessVerified) {
        credentials.push({
            id: `cred_${Date.now()}_vh`,
            userId: '',
            type: 'verified_human',
            status: 'active',
            issuedAt: now,
            expiresAt: oneYear,
            usageCount: 0,
            lastUsedAt: null,
            data: { verifiedAt: now.toISOString() }
        });
    }

    // Age credentials - requires DOB from document
    if (identityData.documentVerified && identityData.dob) {
        const age = calculateAge(identityData.dob);

        if (age >= 18) {
            credentials.push({
                id: `cred_${Date.now()}_a18`,
                userId: '',
                type: 'age_18',
                status: 'active',
                issuedAt: now,
                expiresAt: oneYear,
                usageCount: 0,
                lastUsedAt: null,
                data: { verifiedAge: '18+' } // Zero-knowledge: doesn't reveal actual age
            });
        }

        if (age >= 21) {
            credentials.push({
                id: `cred_${Date.now()}_a21`,
                userId: '',
                type: 'age_21',
                status: 'active',
                issuedAt: now,
                expiresAt: oneYear,
                usageCount: 0,
                lastUsedAt: null,
                data: { verifiedAge: '21+' }
            });
        }
    }

    // Location credential
    if (identityData.documentVerified && identityData.country) {
        credentials.push({
            id: `cred_${Date.now()}_loc`,
            userId: '',
            type: 'location',
            status: 'active',
            issuedAt: now,
            expiresAt: oneYear,
            usageCount: 0,
            lastUsedAt: null,
            data: {
                country: identityData.country,
                state: identityData.state || null
            }
        });
    }

    // Government ID credential
    if (identityData.documentVerified || identityData.digilockerConnected) {
        credentials.push({
            id: `cred_${Date.now()}_gid`,
            userId: '',
            type: 'government_id',
            status: 'active',
            issuedAt: now,
            expiresAt: null, // Doesn't expire
            usageCount: 0,
            lastUsedAt: null,
            data: {
                verified: true,
                source: identityData.digilockerConnected ? 'digilocker' : 'document_scan'
            }
        });
    }

    // Email verified
    if (identityData.emailVerified) {
        credentials.push({
            id: `cred_${Date.now()}_email`,
            userId: '',
            type: 'email_verified',
            status: 'active',
            issuedAt: now,
            expiresAt: null,
            usageCount: 0,
            lastUsedAt: null,
            data: { verified: true }
        });
    }

    // Phone verified
    if (identityData.phoneVerified) {
        credentials.push({
            id: `cred_${Date.now()}_phone`,
            userId: '',
            type: 'phone_verified',
            status: 'active',
            issuedAt: now,
            expiresAt: null,
            usageCount: 0,
            lastUsedAt: null,
            data: { verified: true }
        });
    }

    return credentials;
}

/**
 * Calculate age from date of birth
 */
function calculateAge(dob: string): number {
    const birthDate = new Date(dob);
    const today = new Date();
    let age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();

    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
        age--;
    }

    return age;
}

/**
 * Get credential type info
 */
export function getCredentialTypeInfo(type: string): CredentialType | undefined {
    return CREDENTIAL_TYPES.find(ct => ct.type === type);
}

/**
 * Check if user has required credentials
 */
export function hasRequiredCredentials(
    userCredentials: string[],
    required: string[]
): { hasAll: boolean; missing: string[] } {
    const missing = required.filter(r => !userCredentials.includes(r));
    return {
        hasAll: missing.length === 0,
        missing
    };
}

/**
 * Format credential for display
 */
export function formatCredentialForDisplay(credential: UserCredential): {
    name: string;
    icon: string;
    status: string;
    usageText: string;
} {
    const typeInfo = getCredentialTypeInfo(credential.type);

    return {
        name: typeInfo?.name || credential.type,
        icon: typeInfo?.icon || '📄',
        status: credential.status === 'active'
            ? (credential.expiresAt && new Date(credential.expiresAt) < new Date() ? 'expired' : 'active')
            : credential.status,
        usageText: credential.usageCount > 0
            ? `Used ${credential.usageCount} time${credential.usageCount > 1 ? 's' : ''}`
            : 'Never used'
    };
}
